import { IFormSection } from "@/models/FormSettings";

// Default Dermatology Form Configuration
export const defaultDermatologyForm: IFormSection[] = [
  {
    sectionName: "patientInfo",
    sectionLabel: "Patient Information",
    enabled: true,
    order: 1,
    fields: [
      {
        fieldName: "complaint",
        label: "Chief Complaint",
        type: "textarea",
        required: true,
        enabled: true,
        placeholder: "What is the main skin concern?",
        order: 1,
      },
      {
        fieldName: "duration",
        label: "Duration",
        type: "text",
        required: true,
        enabled: true,
        placeholder: "How long has this been present?",
        order: 2,
      },
      {
        fieldName: "previousTreatment",
        label: "Previous Treatment",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Any previous treatments tried?",
        order: 3,
      },
    ],
  },
  {
    sectionName: "clinicalExamination",
    sectionLabel: "Clinical Examination",
    enabled: true,
    order: 2,
    fields: [
      {
        fieldName: "lesionSite",
        label: "Lesion Site",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Location on body",
        order: 1,
      },
      {
        fieldName: "morphology",
        label: "Morphology",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Describe the appearance",
        order: 2,
      },
      {
        fieldName: "distribution",
        label: "Distribution",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Pattern of distribution",
        order: 3,
      },
      {
        fieldName: "severity",
        label: "Severity",
        type: "select",
        required: false,
        enabled: true,
        options: ["Mild", "Moderate", "Severe"],
        order: 4,
      },
    ],
  },
  {
    sectionName: "dermoscopeFindings",
    sectionLabel: "Dermoscope Findings",
    enabled: true,
    order: 3,
    fields: [
      {
        fieldName: "patterns",
        label: "Dermoscopic Patterns",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Describe dermoscopic findings",
        order: 1,
      },
      {
        fieldName: "finalInterpretation",
        label: "Final Interpretation",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Doctor's interpretation of AI + dermoscopy",
        order: 2,
      },
    ],
  },
  {
    sectionName: "diagnosis",
    sectionLabel: "Diagnosis",
    enabled: true,
    order: 4,
    fields: [
      {
        fieldName: "provisional",
        label: "Provisional Diagnosis",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Primary diagnosis",
        order: 1,
      },
      {
        fieldName: "differentials",
        label: "Differential Diagnoses",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Comma-separated differential diagnoses",
        order: 2,
      },
    ],
  },
  {
    sectionName: "treatmentPlan",
    sectionLabel: "Treatment Plan",
    enabled: true,
    order: 5,
    fields: [
      {
        fieldName: "topicals",
        label: "Topical Medications",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Topical treatments",
        order: 1,
      },
      {
        fieldName: "orals",
        label: "Oral Medications",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Oral medications",
        order: 2,
      },
      {
        fieldName: "lifestyleChanges",
        label: "Lifestyle Changes",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Lifestyle recommendations",
        order: 3,
      },
      {
        fieldName: "investigations",
        label: "Investigations Required",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Any tests or investigations needed",
        order: 4,
      },
    ],
  },
  {
    sectionName: "followUp",
    sectionLabel: "Follow-up",
    enabled: true,
    order: 6,
    fields: [
      {
        fieldName: "date",
        label: "Follow-up Date",
        type: "date",
        required: false,
        enabled: true,
        order: 1,
      },
      {
        fieldName: "reason",
        label: "Follow-up Reason",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "What to review in next visit",
        order: 2,
      },
    ],
  },
];

// Default Cosmetology Form Configuration
export const defaultCosmetologyForm: IFormSection[] = [
  {
    sectionName: "patientInfo",
    sectionLabel: "Patient Information",
    enabled: true,
    order: 1,
    fields: [
      {
        fieldName: "skinType",
        label: "Skin Type (Fitzpatrick)",
        type: "select",
        required: false,
        enabled: true,
        options: ["Type I", "Type II", "Type III", "Type IV", "Type V", "Type VI"],
        order: 1,
      },
      {
        fieldName: "primaryConcern",
        label: "Primary Concern",
        type: "textarea",
        required: true,
        enabled: true,
        placeholder: "Main cosmetic concern (pigmentation, scars, aging, etc.)",
        order: 2,
      },
    ],
  },
  {
    sectionName: "assessment",
    sectionLabel: "Assessment & Analysis",
    enabled: true,
    order: 2,
    fields: [
      {
        fieldName: "findings",
        label: "Clinical Findings",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "What do you observe?",
        order: 1,
      },
      {
        fieldName: "diagnosis",
        label: "Assessment/Diagnosis",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Cosmetic diagnosis",
        order: 2,
      },
      {
        fieldName: "baselineEvaluation",
        label: "Baseline Evaluation",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Current skin condition baseline",
        order: 3,
      },
      {
        fieldName: "contraindicationsCheck",
        label: "Contraindications Check",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Any contraindications noted?",
        order: 4,
      },
    ],
  },
  {
    sectionName: "procedure",
    sectionLabel: "Procedure Details",
    enabled: true,
    order: 3,
    fields: [
      {
        fieldName: "name",
        label: "Procedure Name",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Name of the procedure",
        order: 1,
      },
      {
        fieldName: "goals",
        label: "Treatment Goals",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "What are we trying to achieve?",
        order: 2,
      },
      {
        fieldName: "sessionNumber",
        label: "Session Number",
        type: "number",
        required: false,
        enabled: true,
        placeholder: "Session #",
        order: 3,
      },
      {
        fieldName: "package",
        label: "Package/Plan",
        type: "text",
        required: false,
        enabled: true,
        placeholder: "Treatment package details",
        order: 4,
      },
      {
        fieldName: "productsAndParameters",
        label: "Products & Parameters",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Products used and treatment parameters",
        order: 5,
      },
      {
        fieldName: "immediateOutcome",
        label: "Immediate Outcome",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Results immediately after procedure",
        order: 6,
      },
    ],
  },
  {
    sectionName: "aftercare",
    sectionLabel: "Aftercare & Follow-up",
    enabled: true,
    order: 4,
    fields: [
      {
        fieldName: "instructions",
        label: "Aftercare Instructions",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Post-procedure care instructions",
        order: 1,
      },
      {
        fieldName: "homeProducts",
        label: "Home Products Recommended",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Products to use at home",
        order: 2,
      },
      {
        fieldName: "followUpDate",
        label: "Follow-up Date",
        type: "date",
        required: false,
        enabled: true,
        order: 3,
      },
      {
        fieldName: "expectedResults",
        label: "Expected Results Timeline",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "When to expect results",
        order: 4,
      },
    ],
  },
  {
    sectionName: "consent",
    sectionLabel: "Consent & Risks",
    enabled: true,
    order: 5,
    fields: [
      {
        fieldName: "risksExplained",
        label: "Risks Explained",
        type: "textarea",
        required: false,
        enabled: true,
        placeholder: "Document risks explained to patient",
        order: 1,
      },
      {
        fieldName: "consentConfirmed",
        label: "Consent Confirmed",
        type: "checkbox",
        required: false,
        enabled: true,
        order: 2,
      },
    ],
  },
];
